---
- name: Post Ubuntu Install
  hosts: all
  become: true

  vars:
    reizvihpass: P@ssword
    troickiypass: P@ssword
  
  tasks:
  
  - name: "Update Repository cache"
    ansible.builtin.apt:
      update_cache: yes
    
  - name: "Update cache & Full system update"
    ansible.builtin.apt:
      upgrade: dist
  
  - name: "creating users"  
    user: 
      name: troickiy
      state: present

  - name: "creating users"  
    user: 
      name: reizvih
      state: present
  
  - name: "create groups"
    group:
      name: "{{ item }}"
      state: present
    loop:
      - reizvih
      - troickiy
           
  - name: "add troickiy to groups"
    ansible.builtin.user:
      name: troickiy
      shell: /bin/bash
      groups: troickiy,sudo
      append: yes

  - name: "add reizvih to groups"
    ansible.builtin.user:
      name: reizvih
      shell: /bin/bash
      groups: reizvih,sudo
      append: yes
      
  - name: "put reizvih key to server"
    authorized_key:
       user: reizvih
       state: present
       key: "{{ lookup('file', '/Users/v.reizvih/.ssh/reizvih/id_rsa.pub') }}"
       
  - name: "put troickiy key to server"
    authorized_key:
       user: troickiy
       state: present
       key: "{{ lookup('file', '/Users/v.reizvih/.ssh/troickiy/id_rsa.pub') }}"

  - name: "set password reizvih"
    ansible.builtin.user:
      name: reizvih
      password: "{{ reizvihpass | password_hash('sha512') }}"

  - name: "set password troickiy"
    ansible.builtin.user:
      name: troickiy
      password: "{{ troickiypass | password_hash('sha512') }}"

  - name: "install fail2ban"
    ansible.builtin.apt:
      name: fail2ban
      state: latest

  - name: "outgoing allow"
    community.general.ufw:
      direction: outgoing
      policy: allow

  - name: "incoming deny"
    community.general.ufw:
      direction: incoming
      policy: deny

  - name: "allow ssh port 22"
    community.general.ufw:
      rule: allow
      direction: in
      port: 22
      proto: tcp

  - name: "allow ssh port 53"
    community.general.ufw:
      rule: allow
      direction: in
      port: 53
      proto: udp

  - name: "allow ssh port 80"
    community.general.ufw:
      rule: allow
      direction: in
      port: 80
      proto: tcp

  - name: "allow ssh port 443"
    community.general.ufw:
      rule: allow
      direction: in
      port: 443
      proto: tcp

  - name: "allow ssh port 2222"
    community.general.ufw:
      rule: allow
      direction: in
      port: 2222
      proto: tcp

  - name: "enable ufw"
    community.general.ufw:
      state: enabled

  - name: "Change SSH port to 2222"
    ansible.builtin.lineinfile:
      path: /etc/ssh/ssh_config
      line: Port 2222
      create: yes

  - name: "Disallow SSH password authentication"
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config.d/50-cloud-init.conf
      regexp: "^PasswordAuthentication"
      line: PasswordAuthentication no
      owner: root
      group: root
      mode: '0644'

    