---
- name: Post Ubuntu Install
  hosts: all
  become: yes
  
  tasks:
  
  - apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    
  - apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true
    
  - user: 
      name: reizvih
      state: present
      name: troickiy
      state: present
  
  - group:
      name: "{{ item }}"
      state: present
    loop:
      - reizvih
      - troickiy
     
  - ansible.builtin.user:
      name: reizvih
      shell: /bin/bash
      groups: reizvih,sudo
      append: yes
      
  - ansible.builtin.user:
      name: troickiy
      shell: /bin/bash
      groups: troickiy,sudo
      append: yes
      
  - authorized_key:
       user: reizvih
       state: present
       key: "{{ lookup('file', '/Users/v.reizvih/.ssh/reizvih/rsa.pub') }}"
       
  - authorized_key:
       user: troickiy
       state: present
       key: "{{ lookup('file', '/Users/v.reizvih/.ssh/troickiy/rsa.pub') }}"