---
- name: Post Ubuntu Install
  hosts: all
  become: true

  vars:
    reizvihpass: P@ssword
    troickiypass: P@ssword
  
  tasks:
  
  - name: "Update Repository cache"
    ansible.builtin.apt:
      update_cache: yes
    
  - name: "Update cache & Full system update"
    ansible.builtin.apt:
      upgrade: dist
  
  - name: "creating users"  
    user: 
      name: troickiy
      state: present

  - name: "creating users"  
    user: 
      name: reizvih
      state: present
  
  - name: "create groups"
    group:
      name: "{{ item }}"
      state: present
    loop:
      - reizvih
      - troickiy
           
  - name: "add troickiy to groups"
    ansible.builtin.user:
      name: troickiy
      shell: /bin/bash
      groups: troickiy,sudo
      append: yes

  - name: "add reizvih to groups"
    ansible.builtin.user:
      name: reizvih
      shell: /bin/bash
      groups: reizvih,sudo
      append: yes
      
  - name: "put reizvih key to server"
    authorized_key:
       user: reizvih
       state: present
       key: "{{ lookup('file', '/Users/v.reizvih/.ssh/reizvih/id_rsa.pub') }}"
       
  - name: "put troickiy key to server"
    authorized_key:
       user: troickiy
       state: present
       key: "{{ lookup('file', '/Users/v.reizvih/.ssh/troickiy/id_rsa.pub') }}"

  - name: "set password reizvih"
    ansible.builtin.user:
      name: reizvih
      password: "{{ reizvihpass | password_hash('sha512') }}"

  - name: "set password troickiy"
    ansible.builtin.user:
      name: troickiy
      password: "{{ troickiypass | password_hash('sha512') }}"
    